services:
  mongo:
    image: mongo:7
    container_name: lab2_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: lab2_mongo_express
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "28203:8081"

  admin-mongo:
    image: mrvautin/adminmongo:latest
    container_name: lab2_admin_mongo
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      CONNECTIONSTRING: mongodb://admin:admin123@mongo:27017/admin
      HOST: 0.0.0.0
      PORT: 1234
    ports:
      - "28204:1234"

  cassandra:
    image: cassandra:4.1
    container_name: lab2_cassandra
    restart: unless-stopped
    environment:
      CASSANDRA_CLUSTER_NAME: streaming_cluster
      CASSANDRA_DC: dc1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    ports:
      - "9042:9042"

  cassandra-web:
    image: ipushc/cassandra-web
    container_name: lab2_cassandra_web
    restart: unless-stopped
    depends_on:
      - cassandra
    environment:
      CASSANDRA_HOST_IP: cassandra
    ports:
      - "28200:3000"

  graphdb:
    image: ontotext/graphdb:10.7.3
    container_name: lab2_graphdb
    restart: unless-stopped
    ports:
      - "7200:7200"
    volumes:
      - graphdb_data:/opt/graphdb/home

  redis:
    image: redis:7
    container_name: lab2_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: lab2_redis_commander
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "28119:8081"

volumes:
  mongo_data:
  graphdb_data:
